### ISSUE TITLE
SSL changes required

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/spaceport#6]
Post HTTPS on/off in environment variable for apache container.
On "spaceport start" check that certificates are found, if not ask the path, and copy certificates to dinghy.

**Comment by jockri** [comment]
@Devolicious this is already done, right?

**Comment by bakie** [comment]
@jockri this is done and I have created a new PR to change the logic of the this https://github.com/Kunstmaan/spaceport/pull/21
